language: ruby
jdk: oraclejdk9
rvm: 2.4
before_install: 
  - docker run --name cqf-ruler --rm -dit -p 8080:8080 contentgroup/cqf-ruler:latest
  - sudo chown -R travis ./travis/pull_data.sh
  - sudo chmod +x ./travis/pull_data.sh
  - ./travis/pull_data.sh
  - gem install jekyll
script: ant -buildfile build.xml travis-publish-ig -Dguidename=cqfmeasures -Dspec=http://hl7-fhir.github.io/
services:
  - docker
